name: Production Workflow

run-name: ${{ github.event.head_commit.message }}

env:
  HOSTNAME: "3.123.200.77"
  API_PORT: ${{ vars.API_PORT }}

on:
  push:
    tags: ['v*.*.*']

jobs:
  build:
    name: build-production
    runs-on: ubuntu-latest
    environment: production
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Prepare environment variables
        uses: ./.github/actions/environments
      - name: Run build via Docker
        run: |
          docker build \
            --tag ghcr.io/$CI_REPOSITORY_NAME/api-github:latest \
            --target final \
            --build-arg DOCKER_TAG=$CI_DOCKER_TAG \
            --build-arg API_PORT=$API_PORT .
          docker tag ghcr.io/$CI_REPOSITORY_NAME/api-github:latest \
            ghcr.io/$CI_REPOSITORY_NAME/api-github:$CI_DOCKER_TAG
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push built image to Container Registry
        run: |
          docker push ghcr.io/$CI_REPOSITORY_NAME/api-github:latest
          docker push ghcr.io/$CI_REPOSITORY_NAME/api-github:$CI_DOCKER_TAG

  deploy:
    name: deploy-production
    runs-on: [production-deploy]
    environment:
      name: production
      url: http://${{ env.HOSTNAME }}:${{ env.API_PORT }}
    needs: [build]
    container:
      image: docker:28.1.1-cli
      env:
        PROJECT_NAME: web-service-github
        DOCKER_NAME: api-github
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - uses: actions/checkout@v4
      - name: Install bash to job image (docker:28.1.1-cli)
        run: |
          apk add --no-cache bash
      - name: Prepare environment variables
        uses: ./.github/actions/environments
      - name: Run compose via Docker
        run: |
          DOCKER_TAG=$CI_DOCKER_TAG \
          DOCKER_IMAGE=ghcr.io/$CI_REPOSITORY_NAME/api-github \
          docker compose --profile prod up \
            -d --no-build --force-recreate \
            --pull missing

  release:
    name: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [deploy]
    steps:
      - uses: actions/checkout@v4
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          body: "Example description"