name: Production Workflow

run-name: ${{ github.event.head_commit.message }}

env:
  HOSTNAME: "3.123.200.77"
  API_PORT: ${{ vars.API_PORT }}

on:
  push:
    tags: ['v*.*.*']

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Prepare environment variables
        uses: ./.github/actions/environments
      - name: Run build via Docker
        run: |
          docker build \
            --tag it/rest-api:$CI_DOCKER_TAG \
            --target final \
            --build-arg DOCKER_TAG=$CI_DOCKER_TAG \
            --build-arg API_PORT=$API_PORT .
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push built image to Container Registry
        run: |
          docker tag it/rest-api:$CI_DOCKER_TAG ghcr.io/jikol/rest-api:$CI_DOCKER_TAG
          docker push ghcr.io/jikol/rest-api:$CI_DOCKER_TAG