name: Staging Workflow

run-name: ${{ github.event.head_commit.message }}

env:
  HOSTNAME: "3.123.200.77"
  API_PORT: ${{ vars.API_PORT }}

on:
  push:
    branches: [develop]

jobs:
  test:
    name: test-staging
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - name: Run tests via Docker
        run: |
          docker build \
            --target test \
            --build-arg API_PORT=$API_PORT \
            --output=type=cacheonly .

  build:
    name: build-staging
    runs-on: ubuntu-latest
    environment: staging
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - name: Run build via Docker
        run: |
          docker build \
            --tag web-service/api-github:staging \
            --target final \
            --build-arg DOCKER_TAG=latest \
            --build-arg API_PORT=$API_PORT .
      - name: Save built image via Docker
        run: |
          docker save -o api-github-staging.tar web-service/api-github:staging
      - uses: actions/upload-artifact@v4
        with:
          name: staging-docker-image
          path: api-github-staging.tar

  deploy:
    name: deploy-staging
    runs-on: [staging-deploy]
    environment:
      name: staging
      url: http://${{ env.HOSTNAME }}:${{ env.API_PORT }}
    needs: [test, build]
    container:
      image: docker:28.1.1-cli
      env:
        DOCKER_NAME: api-github-staging
        DOCKER_IMAGE: ghcr.io/jikol/api-gitlab
        DOCKER_TAG: staging
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: staging-docker-image
          path: api-github-staging.tar
      - name: Load built image via Docker
        run: |
          docker load -i api-github-staging.tar
      - name: Run compose via Docker
        run: |
          docker compose --profile prod up \
            -d --no-build --force-recreate \
            --pull missing